name: Build Client and Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v4
        id: setup-rye
        with:
          version: "0.42.0"
          working-directory: ./client
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies and Build
        run: |
          rye sync --no-lock 
          rye build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: client/dist/*
  
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate lowercase repository name
        run: echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: "${{ github.repository }}"

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: Containerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:latest
