name: Build and Push Client Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v4
        id: setup-rye
        with:
          version: "0.42.0"
          working-directory: ./client
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install gcc-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 13
          rye sync --no-lock

      - name: Build with Nuitka
        run: rye run python -m nuitka --standalone --onefile src/client

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: client/client.bin
          include-hidden-files: true
