name: Build and Push Client Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v4
        id: setup-rye
        with:
          version: "0.42.0"
          working-directory: ./client
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies and Build
        run: |
          rye sync --no-lock 
          rye build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: client/dist
          include-hidden-files: true
